name: '🤖 自动化工作流失败报告'
description: '由 GitHub Actions 自动创建，用于报告工作流运行失败。'
title: "🚨 工作流失败: 自动更新Mod翻译"
labels: ["bug", "CI/CD", "automated report"]
assignees: 'Laotian21'

body:
  - type: textarea
    id: failure-details
    attributes:
      label: 失败详情
      description: "以下是由 GitHub Actions 自动生成的失败报告。"
      value: |
        请在此处查看由工作流自动填充的详细失败信息。
    validations:
      required: true
